---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
covid_data <- read_csv("data/covid_confirmed_usafacts.csv", trim_ws=T,
                       col_types=cols(countyFIPS=col_factor(),
                                      "County Name"=col_character(),
                                      State=col_factor(),
                                      stateFIPS=col_factor()))
```

## Data

Load climate station metadata

```{r}
mshr <- read_fwf("data/mshr_enhanced_202003.txt",
         fwf_cols(source_id=21,
                  source=11,
                  begin_date=9,
                  end_date=9,
                  station_status=21,
                  
                  #ncdcstn_id=20, icao_id=20, wban_id=20, faa_id=20, nwsli_id=20, wmo_id=20, coop_id=20, transmittal_id=20,
                  skip=21*8,
                  ghcnd_id=21,
                  
                  name=101,
                  #name_principal_short=31, name_coop=101, name_coop_short=31, name_publication=101, name_alias=101,
                  skip2=31+101+31+101+101,
                  
                  #nws_clim_div=10, nws_clim_div_name=40, 
                  skip3=11+41,
                  
                  state_prov=11, county=51, nws_st_code=3, fips_country_code=3, fips_country_name=101,
                  
                  #nws_region=31, nws_wfo=11, 
                  skip7=31+11,
                  
                  #elev_ground=40, elev_ground_unit=20, elev_barom=40, elev_barom_unit=20, elev_air=40, elev_air_unit=20, elev_zerodat=40, elev_zerodat_unit=20, elev_unk=40, elev_unk_unit=20, 
                  skip4=(41+21)*5,
                  
                  #lat_dec=21, lon_dec=21, lat_lon_precision=11,
                  skip5=21+21+11,
                  
                  #relocation=63, utc_offset=17, obs_env=41, platform=101, ghcnmlt_id=21,
                  skip6=63+17+41+101+21,
                  
                  county_fips_code=6),
         col_types=list(station_status=col_factor(),
                        ghcnd_id=col_character(),
                        name=col_character(),
                        state_prov=col_factor(),
                        county=col_character(),
                        fips_country_code=col_factor(),
                        begin_date=col_date("%Y%m%d"),
                        end_date=col_date("%Y%m%d"),
                        county_fips_code=col_factor(),
                        .default=col_skip())) %>%
  filter(!is.na(county_fips_code), is.na(station_status) | station_status != "CLOSED") %>% 
  select(-station_status)

write_csv(mshr, "mshr.csv")
```

Load weather data; assign county IDs; compute means over counties.

```{r}
pds <- read_csv("data/ghcnd-pds_2020.csv",
                col_names=c("ghcnd_id", "date", "element", "value", "mflag", "qflag", "sflag", "obs_time"),
                col_types=cols(ghcnd_id=col_character(), date=col_date(format="%Y%m%d"), element=col_factor(), value=col_double(),
                               .default=col_skip()),
                progress=T) %>% 
  left_join(mshr[, c("ghcnd_id", "county_fips_code")]) %>% 
  group_by(county_fips_code, date, element) %>%
    summarise(value=mean(value, na.rm = TRUE))

pds <- pds[,] %>% pivot_wider(names_from=element, values_from=value) %>%
  select(county_fips_code, date, PRCP, TMIN, TMAX)
write_csv(pds, "pds.csv")
pds
```


## Preprocess

```{r}
covid_data = covid_data %>% 
  # Pivot to long
  pivot_longer(cols=contains("/"), names_to="date", values_to="cases") %>% 
  # Date parsing
  mutate(date=parse_date(date, format="%m/%d/%y")) %>% 
  arrange(stateFIPS, countyFIPS, date) %>%

  # Compute cumulative cases
  group_by(countyFIPS) %>% 
    arrange(date) %>% mutate(cum_cases.county=cumsum(cases)) %>% 
  ungroup() %>% 
  group_by(stateFIPS) %>% 
    arrange(date) %>% mutate(cum_cases.state=cumsum(cases)) %>% 
  ungroup() %>% 
  
  # Find first day with 5 cumulative cases
  group_by(countyFIPS) %>%
    group_modify(~ {
      mutate(., first_day_cum5.county=pull(.[which(.$cum_cases.county >= 5)[1],], "date"))
    }) %>% 
  ungroup() %>% 
  group_by(stateFIPS) %>%
    group_modify(~ {
      mutate(., first_day_cum5.state=pull(.[which(.$cum_cases.state >= 5)[1],], "date"))
    }) %>%
  ungroup()
```

### Join weather  data

```{r}
data_joined <- data %>% left_join(psd, by=c("countyFIPS" = "county_fips_code", "date"))
write_csv(data_joined, "data_joined.csv")
data_joined <- read_csv("data_joined.csv", col_types=cols(PRCP=col_double(), TMAX=col_double(), TMIN=col_double()))
```


### Fetch and join weather data


```{r}
data_joined %>% ggplot(aes(x=first_day_cum5.county)) + geom_histogram()
```


```{r}
data_joined %>% ggplot(aes(x=date, y=cum_cases.county, color=State)) + geom_smooth()# , color=State)) + geom_smooth()
```

```{r}
data_joined %>% ggplot(aes(x=date, y=TMIN, color=State)) + geom_smooth()
```

```{r}
data_joined %>% ggplot(aes(x=TMAX, y=cases)) + geom_point()
```

The second group on the right are Florida and Louisiana, states exceptionally hard-hit by the pandemic:
```{r}
data_joined %>% filter(!(State %in% c("FL", "LA"))) %>% ggplot(aes(x=TMAX, y=cases, color=State)) + geom_point()
```

```{r}
data_joined %>% 
  group_by(countyFIPS) %>% 
    mutate(tmax_z=(TMAX-mean(TMAX, na.rm=TRUE))/sd(TMAX, na.rm=TRUE)) %>% 
  ungroup() %>%
  ggplot(aes(x=tmax_z, y=cases, color=State)) + geom_point()
```

```{r}
data_joined = data_joined %>% 
  group_by(countyFIPS) %>% 
    mutate(tmax_z=(TMAX-mean(TMAX, na.rm=TRUE))/sd(TMAX, na.rm=TRUE)) %>% 
  ungroup() %>%
  mutate(tmax_1=lag(TMAX, 1), tmax_2=lag(TMAX, 2), tmax_3=lag(TMAX, 3), tmax_4=lag(TMAX, 4), tmax_5=lag(TMAX, 5),
         tmax_z1=lag(tmax_z, 1), tmax_z2=lag(tmax_z, 2), tmax_z3=lag(tmax_z, 3), tmax_z4=lag(tmax_z, 4), tmax_z5=lag(tmax_z, 5))

data_joined %>%
  pivot_longer(cols=starts_with("tmax_z")) %>%
  ggplot(aes(x=value, y=cases)) + geom_point() + facet_grid(~name)
```

```{r}
library(lme4)

data_lm <- data_joined %>% 
  mutate(days_since_first5=date - first_day_cum5.county) %>% 
  filter(days_since_first5 >= 0)

lm <- lmer(cases ~ tmax_4 + tmax_5 + days_since_first5 + (1 | State/countyFIPS), data=data_lm)
summary(lm)

data_lm %>% ggplot(aes(x=days_since_first5, y=log(cases), color=State)) + geom_point()
```
```{r}
# Load county population data
population <- read_csv("data/cc-est2018-alldata.csv")
# TODO some data loss here because county fips codes don't match up -- they're 3 digits in census data, but 5 in NCDC
population <- population %>% filter(YEAR == 11, AGEGRP == 0) %>% transmute(State=as.double(STATE), "County Name"=CTYNAME, population=TOT_POP)
data_joined <- data_joined %>% left_join(population, by=c("stateFIPS" = "State", "County Name"))
```

```{r}
library(deSolve)
## Create an SIR function
sir <- function(time, state, parameters) {

  with(as.list(c(state, parameters)), {

    dS <- -beta * S * I
    dI <-  beta * S * I - gamma * I
    dR <-                 gamma * I

    return(list(c(dS, dI, dR)))
  })
}

### Set parameters
## beta: infection parameter; gamma: recovery parameter
R0 = 2.25
GAMMA = 1 / 9
## Time frame
times      <- seq(0, 160, by = 1)

# Calculate expected infections based on SIR curve for a county df, and add to county df.
compute_sir <- function(R0, county_df, key) {
  first_day_cum5 = unique(county_df$first_day_cum5.county)
  N = unique(county_df$population)
  I = 5 / N
  S = (N - I) / N
  
  print(c(N, max(county_df$cum_cases.county)))
  init <- c(S = S, I = I, R = 0.0)
  params <- c(beta=R0 * GAMMA, gamma=GAMMA)
  sir_result = data.frame(ode(y=init, times=times, func=sir, parms=params)) %>% 
    transmute(date=time + first_day_cum5,
              sir_cum_cases=round(I * N + R * N))
  
  return(sir_result)
}

R0_options = c(1.4, 1.5, 2.25)
add_sirs <- function(county_df, key) {
  for (r0 in R0_options) {
    sir_result = compute_sir(r0, county_df, key)
    names(sir_result) = paste(names(sir_result), r0, sep=".")
    county_df = county_df %>% left_join(sir_result, by=c("date" = paste("date", r0, sep=".")))
  }
  
  return(county_df)
}

# Compute SIR statistics
test_counties = sample(data_joined$countyFIPS, 500)
data_joined %>% filter(countyFIPS %in% test_counties) %>% 
  group_by(countyFIPS) %>% group_modify(add_sirs) %>% 
  ggplot(aes(x=cum_cases.county, color=countyFIPS)) +
  geom_point(aes(y=sir_cum_cases.1.5))
#data_joined %>% filter(countyFIPS==48457) %>% group_by(countyFIPS) %>% group_modify(add_sir) %>%
#  ggplot(aes(x=cum_cases.county, y=sir_cum_cases)) + geom_point()

data_joined %>% ggplot(aes(x=date, y=sir_cum_cases.2.25)) + geom_line()
```

